/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosUsoRouteImport } from './routes/termos-uso'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PoliticaPrivacidadeRouteImport } from './routes/politica-privacidade'
import { Route as IndexRouteImport } from './routes/index'

const TermosUsoRoute = TermosUsoRouteImport.update({
  id: '/termos-uso',
  path: '/termos-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaPrivacidadeRoute = PoliticaPrivacidadeRouteImport.update({
  id: '/politica-privacidade',
  path: '/politica-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-uso': typeof TermosUsoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-uso': typeof TermosUsoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/politica-privacidade': typeof PoliticaPrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos-uso': typeof TermosUsoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/politica-privacidade' | '/sitemap.xml' | '/termos-uso'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/politica-privacidade' | '/sitemap.xml' | '/termos-uso'
  id:
    '__root__' | '/' | '/politica-privacidade' | '/sitemap.xml' | '/termos-uso'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PoliticaPrivacidadeRoute: typeof PoliticaPrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosUsoRoute: typeof TermosUsoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-uso': {
      id: '/termos-uso'
      path: '/termos-uso'
      fullPath: '/termos-uso'
      preLoaderRoute: typeof TermosUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-privacidade': {
      id: '/politica-privacidade'
      path: '/politica-privacidade'
      fullPath: '/politica-privacidade'
      preLoaderRoute: typeof PoliticaPrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PoliticaPrivacidadeRoute: PoliticaPrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosUsoRoute: TermosUsoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
